# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ParaPups
email: paranoidpuppies@gmail.com
description: >
  The personal website of Lucky "Adi" C. Acro-Santos, professional loser and
  self-domesticated chimp with an affinity for anthropomorphic canids.
  Expect art and random blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.parapups.us" # the base hostname & protocol for your site
twitter_username: ParanoidPuppies
github_username:  ParaPups
telegram_username: ParaPups
instagram_username: ParanoidPuppies

permalink: "/:categories/:title:output_ext"

posts:
  gallery:
    output: true
    permalink: "/gallery/:title:output_ext"
